version: "3.8"

services:
  maildev:
    container_name: "docker_maildev"
    image: maildev/maildev
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "${MAILDEV_PORT}:80"
      - "${SMTP_PORT}:25"
    restart: always
